### ISSUE TITLE
Cannot read property 'serverlessMonoRepo' of undefined

### ISSUE THREAD

**Issue by ineffyble** [Butterwire/serverless-plugin-monorepo#1]
Just installed the plugin to my package's dev dependencies and added it to serverless.yml.

Attempting to run `sls deploy` now gives below error:

```Serverless plugin "serverless-plugin-monorepo" initialization errored: Cannot read property 'serverlessMonoRepo' of undefined```

**Comment by martin-css** [comment]
No problem. Was going to post this is fixed in v0.2.0 but you obviously saw this before I could reply!
