### ISSUE TITLE
please release ;-)

### ISSUE THREAD

**Issue by lepirlouit** [Butterwire/serverless-plugin-monorepo#12]
Hello,

Could you please release a new version with your latest commit.
Containing the fix for #11

Kind Regards,

**Comment by martin-css** [comment]
Sorry folks, was waiting to hear if there was any further feedback on #11 to confirm issue was fixed - then forgot I hadn't released it.

v0.8.0 is now available on npm.

**Comment by lepirlouit** [comment]
Thanks for the release
