### ISSUE TITLE
 Error: EISDIR: illegal operation on a directory, symlink

### ISSUE THREAD

**Issue by jluterek** [Butterwire/serverless-plugin-monorepo#16]
I am getting this error when using the plugin.  This happens when the package already exists in node_modules and the plugin attempts to create a symlink anyway.

The error originates from this code:

```
async function link (target, f, type) {
  await fs.ensureDir(path.dirname(f))
  await fs.symlink(target, f, type)
    .catch(e => {
      if (e.code === 'EEXIST') {
        return
      }
      throw e
    })
}
```

**Comment by martin-css** [comment]
Now fixed in v0.9.0, thanks.
