### ISSUE TITLE
module resolution breaks on node 12.17 and node 14

### ISSUE THREAD

**Issue by Audarth** [Butterwire/serverless-plugin-monorepo#20]
There's an issue with module resolution on newer version of nodes due to changes to require.resolve. see [here](https://github.com/nodejs/node/issues/27583) Interesting enough it only broke on node 12 with the release of 12.17.0

This appears to be easily fixed by changing
```
// Get package file path
    const pkg = require.resolve(path.join(name, 'package.json'), { paths })
```
to

```
// Get package file path
    const pkg = require.resolve('./' + path.join(name, 'package.json'), { paths })
```

**Comment by martin-css** [comment]
Now fixed in v0.10.0
