### ISSUE TITLE
Attempt to remove node_modules when it's not emtpy

### ISSUE THREAD

**Issue by mars-lan** [Butterwire/serverless-plugin-monorepo#25]
During the `clean` step, the plugin assumes that it's okay to remove the entire `node_modules` if there's only scoped packages left: https://github.com/Butterwire/serverless-plugin-monorepo/blob/master/src/index.ts#L143 

I'm not sure the logic behind that, but if you happen to have a `node_modules` with only non-hoisted scoped packages, it'll lead to the following error

```
Serverless: Cleaning dependency symlinks
 
  Error --------------------------------------------------
 
  Error: ENOTEMPTY: directory not empty, rmdir '<package_root>/node_modules'
```

**Comment by martin-css** [comment]
A check has now been added to ensure the directory is truly empty before deleting.
